import {
  GranjaResidencial,
  Paineiras,
  Park395,
  ResidencialAldeia,
  ResidencialElisabeteI,
  ResidencialPaisagem,
  ResidencialVistaAlegreII,
  StudioVertentes,
} from '../assets';

const readyProperties = [
  {
    image: ResidencialPaisagem,
    name: 'Residencial Paisagem',
    address: 'Av. Das Cruzadas, 170 - Cotia - SP',
    rooms: 0,
    bathrooms: 0,
    bedrooms: 0,
    parkingSpaces: 0,
    status: 'ready',
  },
  {
    image: Park395,
    name: 'Park 395',
    address: 'Rua das Gardênias 395 - Taboão da Serra - São Paulo, SP',
    area: '64m2 a 128m2',
    rooms: 0,
    bathrooms: 0,
    bedrooms: 0,
    parkingSpaces: 0,
    status: 'ready',
  },
  {
    image: Paineiras,
    name: 'Paineiras',
    address: 'R. São Francisco, 21 - Parque Jane - Embu das Artes - SP',
    area: '50m2',
    rooms: 0,
    bathrooms: 0,
    bedrooms: 0,
    parkingSpaces: 0,
    status: 'ready',
  },
  {
    image: ResidencialAldeia,
    name: 'Residencial Aldeia',
    address: 'Estrada da Aldeia, 1052 - Granja Viana - São Paulo, SP',
    area: '150m2',
    rooms: 0,
    bathrooms: 0,
    bedrooms: 0,
    parkingSpaces: 0,
    status: 'ready',
  },
];

const underConstructionProperties = [
  {
    image: ResidencialVistaAlegreII,
    name: 'Residencial Vista Alegre II',
    address: 'R​​​​ua Alberto Correa Francfort, ​44 - ​Embu das Artes - São Paulo, SP',
    area: '50m2 e 52m2',
    rooms: 0,
    bathrooms: 0,
    bedrooms: 0,
    parkingSpaces: 0,
    status: 'under_construction',
  },
  {
    image: ResidencialElisabeteI,
    name: 'Residencial Jd Elisabete I',
    address: 'Rua Manoel Maria Fernandes, 330',
    area: '47m2 e 48m2',
    rooms: 0,
    bathrooms: 0,
    bedrooms: 0,
    parkingSpaces: 0,
    status: 'under_construction',
  },
  {
    image: ResidencialElisabeteI,
    name: 'Residencial Jd Elisabete II',
    address: 'Rua Manoel Maria Fernandes, 330',
    area: '47m2 e 48m2',
    rooms: 0,
    bathrooms: 0,
    bedrooms: 0,
    parkingSpaces: 0,
    status: 'under_construction',
  },
  {
    image: GranjaResidencial,
    name: 'Granja Residencial',
    address: 'Estrada da Aldeia, 7509 - Granja Viana - SP',
    area: '57m2 e 61m2',
    rooms: 0,
    bathrooms: 0,
    bedrooms: 0,
    parkingSpaces: 0,
    status: 'under_construction',
  },
  {
    image: StudioVertentes,
    name: 'Studio Vertentes',
    address: 'R. Benedito Branco de Abreu, 12',
    area: '23m2',
    rooms: 0,
    bathrooms: 0,
    bedrooms: 0,
    parkingSpaces: 0,
    status: 'under_construction',
  },
];

export { readyProperties, underConstructionProperties };
